-- Session 09 (Messaging). Conversation/ConversationParticipant/Message — the
-- ONE canonical messaging system for the whole platform. See schema.prisma's
-- "Messaging (Session 09)" section header and docs/MESSAGING.md for the
-- full contract.

-- CreateEnum
CREATE TYPE "ConversationType" AS ENUM ('direct', 'group', 'cohort_broadcast');

-- AlterEnum: reserve the 'message' AssetEntityType value now so a later,
-- SEPARATE migration can add the asset_attachments RLS branch that
-- references it. Postgres cannot use a newly added enum value inside the
-- same transaction that adds it (each migration file is its own
-- transaction), so this deliberately does NOT reference 'message' anywhere
-- else in this file.
ALTER TYPE "AssetEntityType" ADD VALUE 'message';

-- CreateTable
CREATE TABLE "conversations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" "ConversationType" NOT NULL,
    "context_cohort_id" UUID,
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_message_at" TIMESTAMPTZ(6),

    CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "conversation_participants" (
    "conversation_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_read_at" TIMESTAMPTZ(6),

    CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("conversation_id","user_id")
);

-- CreateTable
CREATE TABLE "messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "conversation_id" UUID NOT NULL,
    "sender_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "sent_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "conversations_created_by_idx" ON "conversations"("created_by");
CREATE INDEX "conversations_context_cohort_id_idx" ON "conversations"("context_cohort_id");
CREATE INDEX "conversation_participants_user_id_idx" ON "conversation_participants"("user_id");
CREATE INDEX "messages_conversation_id_sent_at_idx" ON "messages"("conversation_id", "sent_at");
CREATE INDEX "messages_sender_id_idx" ON "messages"("sender_id");

-- A cohort_broadcast conversation must record which cohort it broadcasts
-- to; direct/group conversations leave it null. Prisma's schema DSL has no
-- CHECK syntax, so this is hand-authored directly, same convention as the
-- assets_files migration's resources_url_or_asset_check.
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_cohort_broadcast_context_check"
  CHECK (("type" <> 'cohort_broadcast') OR ("context_cohort_id" IS NOT NULL));

-- AddForeignKey
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_context_cohort_id_fkey" FOREIGN KEY ("context_cohort_id") REFERENCES "cohorts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Row-Level Security
--
-- NOTE ON RECURSION (read before touching any policy below): a naive
-- SELECT policy on conversation_participants that subqueries
-- conversation_participants ITSELF (to let a participant see fellow
-- participants' rows) causes "infinite recursion detected in policy" —
-- Postgres re-applies a table's own RLS policy to every subquery reference
-- to that same table, including references generated by the policy's own
-- rewrite, and a self-referencing qual never bottoms out. This is the same
-- failure class documented in the assessment_core and assets_files
-- migrations (a two-table policy cycle), just triggered by ONE table
-- referencing itself instead of two tables referencing each other.
--
-- Fix: app_current_user_conversation_ids(), a SECURITY DEFINER function
-- that runs as the migrator/table-owner role (which bypasses RLS by
-- default, same as any owner-run query) and is therefore opaque to the
-- RLS rewriter — referencing it from a policy never re-triggers
-- conversation_participants' own SELECT policy. SET search_path pins it
-- against search-path-injection (a real, documented SECURITY DEFINER
-- footgun), per CLAUDE_BUILD_RULES.md section 6.
CREATE FUNCTION app_current_user_conversation_ids() RETURNS SETOF UUID
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT conversation_id FROM conversation_participants
  WHERE user_id = nullif(current_setting('app.user_id', true), '')::uuid
$$;

ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "conversation_participants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;

-- conversations: visible to a participant (via the helper function above)
-- or super_admin. Created by whoever inserts it (the real relationship/
-- permission validation — messages.send + assertCanMessage — happens in
-- src/lib/messaging.ts before this INSERT ever runs; this policy is only
-- the DB-level backstop, same shape as assets_write's "any authenticated
-- user may write their own row" plus an app-layer gate in front of it).
-- UPDATE is restricted to participants (application code only ever
-- touches last_message_at through it — see src/lib/messaging.ts).
CREATE POLICY conversations_select ON "conversations" FOR SELECT USING (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversations"."id" IN (SELECT app_current_user_conversation_ids())
);

CREATE POLICY conversations_write ON "conversations" FOR INSERT WITH CHECK (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversations"."created_by" = nullif(current_setting('app.user_id', true), '')::uuid
);

CREATE POLICY conversations_update ON "conversations" FOR UPDATE USING (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversations"."id" IN (SELECT app_current_user_conversation_ids())
) WITH CHECK (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversations"."id" IN (SELECT app_current_user_conversation_ids())
);

-- conversation_participants: a user always sees their own participant row;
-- the function-based branch additionally lets them see fellow participants
-- of a conversation they're themselves in (e.g. rendering "you and 3
-- others"). INSERT is restricted to the conversation's creator — the whole
-- initial participant set (including the creator's own row) is written in
-- one transaction at conversation-creation time (see startConversation());
-- there is no add-participant-later feature. UPDATE is self-only (marking
-- your own last_read_at). No DELETE policy at all — no leave-conversation
-- feature, so DELETE is denied outright for every role.
CREATE POLICY conversation_participants_select ON "conversation_participants" FOR SELECT USING (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversation_participants"."user_id" = nullif(current_setting('app.user_id', true), '')::uuid
  OR "conversation_participants"."conversation_id" IN (SELECT app_current_user_conversation_ids())
);

CREATE POLICY conversation_participants_write ON "conversation_participants" FOR INSERT WITH CHECK (
  current_setting('app.is_super_admin', true) = 'true'
  OR EXISTS (
    SELECT 1 FROM conversations c
    WHERE c."id" = "conversation_participants"."conversation_id"
      AND c."created_by" = nullif(current_setting('app.user_id', true), '')::uuid
  )
);

CREATE POLICY conversation_participants_update ON "conversation_participants" FOR UPDATE USING (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversation_participants"."user_id" = nullif(current_setting('app.user_id', true), '')::uuid
) WITH CHECK (
  current_setting('app.is_super_admin', true) = 'true'
  OR "conversation_participants"."user_id" = nullif(current_setting('app.user_id', true), '')::uuid
);

-- messages: append-only (no UPDATE/DELETE policy at all — same shape as
-- lesson_versions/audit_events), participant-gated for both read and
-- write. This is the core "server-side participant authorization"
-- acceptance criterion enforced at the DB level, not just in application
-- code (src/lib/messaging.ts's sendMessage() checks the same thing before
-- ever reaching this INSERT).
CREATE POLICY messages_select ON "messages" FOR SELECT USING (
  current_setting('app.is_super_admin', true) = 'true'
  OR "messages"."conversation_id" IN (SELECT app_current_user_conversation_ids())
);

CREATE POLICY messages_write ON "messages" FOR INSERT WITH CHECK (
  current_setting('app.is_super_admin', true) = 'true'
  OR (
    "messages"."sender_id" = nullif(current_setting('app.user_id', true), '')::uuid
    AND "messages"."conversation_id" IN (SELECT app_current_user_conversation_ids())
  )
);
